package com.sample
 
import com.sample.Window;

global Window window;

declare Dialog
	question: String
	answers: String[]
end

declare Answer
	dialog: Dialog
	dialogAnswer: String
end

rule "Init"
	when
	then
		insert(
		new Dialog(
		"Search your feelings. Why are you traveling",
		new String[] {		"Vacation? Now that's a word I haven't heard in a long, long time.",
		"I just want to teleport off this rock"}
		));
		window = new Window();
		insert(window);
end

rule "D"
	when a: Dialog()
	then 
		String odp = window.askUser(a.getQuestion(),a.getAnswers());
		Answer ans = new Answer(a, odp);
		insert(ans);
end

rule "Q2"
	when Answer(
		d: dialog, 
		d.getQuestion() == "Search your feelings. Why are you traveling"
		&& getDialogAnswer() == "Vacation? Now that's a word I haven't heard in a long, long time.")
	then
	Dialog td = new Dialog(
		"What could you use a break from?",
		new String[] {"The same faces at the cantina","The city","Work"});
	String ta = window.askUser(td.getQuestion(),td.getAnswers());
	insert(new Answer (td,ta));
end

rule "Q5"
	when Answer(
		d: dialog, d.getQuestion == "What could you use a break from?" 
		&& getDialogAnswer() == "The same faces at the cantina"
		)
	then 
	Dialog td = new Dialog(
		"Are you self-destructive?",
		 new String[]{"No","Yes"}
		 );
	String ta = window.askUser(td.getQuestion(),td.getAnswers());
	insert(new Answer( td,ta));
end

rule "Q3"
	when Answer(
		d:dialog,d.getQuestion == "What could you use a break from?" &&
		getDialogAnswer() == "The city"
		)
	then
	Dialog td = new Dialog(
		"Sounds like you need to commune with nature.",
		new String[] {"OK but I'm not sleeping outside, rigth","Yes"}
		);
	String ta = window.askUser(td.getQuestion(),td.getAnswers());
	insert(new Answer(td,ta));
end

rule "Q4"
	when Answer(
		d:dialog, d.getQuestion == "What could you use a break from?"
		&& getDialogAnswer() == "Work"
	)
	then
	Dialog tempDialog = new Dialog(
		"What line of work are you in?",
		new String[] {"Business","Retail","Creative field"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q6"
	when Answer(
		d:dialog, d.getQuestion == "Are you self-destructive?"
		&& getDialogAnswer() == "Yes"
	)
	then
	Dialog tempDialog = new Dialog(
		"Mentally or physically?",
		new String[] {"Mentally","Physically"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q7"
	when Answer(
		d:dialog, d.getQuestion == "Are you self-destructive?"
		&& getDialogAnswer() == "No"
	)
	then
	Dialog tempDialog = new Dialog(
		"Are you social?",
		new String[] {"No","Yes","I prefer animals over people"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q8"
	when Answer(
		d:dialog, d.getQuestion == "Are you social?"
		&& getDialogAnswer() == "No"
	)
	then
	Dialog tempDialog = new Dialog(
		"By choice?",
		new String[] {"No, most of my friends have moved away.","Yes. I can't stand pathetic life forms"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q9"
	when Answer(
		d:dialog, d.getQuestion == "By choice?"
		&& getDialogAnswer() == "Yes. I can't stand pathetic life forms"
	)
	then
	Dialog tempDialog = new Dialog(
		"What color is your lightsaber?",
		new String[] {"Blue","Red"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q9_ilum"
	when Answer(
		d:dialog, d.getQuestion == "What color is your lightsaber?"
		&& getDialogAnswer() == "Blue"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nILUM",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q9_jakku"
	when Answer(
		d:dialog, d.getQuestion == "What color is your lightsaber?"
		&& getDialogAnswer() == "Red"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\nJAKKU",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q11"
	when Answer(
		d:dialog, d.getQuestion == "Are you social?"
		&& getDialogAnswer() == "Yes"
	)
	then
	Dialog tempDialog = new Dialog(
		"Describe your friends.",
		new String[] {"A bunch of scruffy-lookin' nrefherders", "A ton of party animals. Mos Einsley is old news.", "Tight-knit. i'd do anything for them."}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q11_MALASTARE"
	when Answer(
		d:dialog, d.getQuestion == "Describe your friends."
		&& getDialogAnswer() == "A bunch of scruffy-lookin' nrefherders"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n MALASTARE",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q10"
	when Answer(
		d:dialog, d.getQuestion == "By choice?"
		&& getDialogAnswer() == "No, most of my friends have moved away."
	)
	then
	Dialog tempDialog = new Dialog(
		"Aw. QQ. Stop puting and go find them!",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q10_5"
	when Answer(
		d:dialog, d.getQuestion == 		"Aw. QQ. Stop puting and go find them!"
		&& getDialogAnswer() == "OK"
	)
	then
	Dialog tempDialog = new Dialog(
		"Describe your friends.",
		new String[] {"A bunch of scruffy-lookin' nrefherders", "A ton of party animals. Mos Einsley is old news.", "Tight-knit. i'd do anything for them."}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q13"
	when Answer(
		d:dialog, d.getQuestion == "Describe your friends."
		&& getDialogAnswer() == "A ton of party animals. Mos Einsley is old news."
	)
	then
	Dialog tempDialog = new Dialog(
		"Pick your poison.",
		new String[] {"Glyterrill","Death Sticks","Rhyll"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end


rule "Q13_MALASTARE"
	when Answer(
		d:dialog, d.getQuestion == "Pick your poison."
		&& getDialogAnswer() == "Glyterrill"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n MALASTARE",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q13_CORUSCANT"
	when Answer(
		d:dialog, d.getQuestion == "Pick your poison."
		&& getDialogAnswer() == "Death Sticks"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n CORUSCANT",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q13_RYLOTH"
	when Answer(
		d:dialog, d.getQuestion == "Pick your poison."
		&& getDialogAnswer() == "Rhyll"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n RYLOTH",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q14"
	when Answer(
		d:dialog, d.getQuestion == "Describe your friends."
		&& getDialogAnswer() == "Tight-knit. i'd do anything for them."
	)
	then
	Dialog tempDialog = new Dialog(
		"How do you spend your time together?",
		new String[] {"Playing video games",
		 "Long talks",
		  "Eat sushi"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q14_RYLOTH"
	when Answer(
		d:dialog, d.getQuestion == "How do you spend your time together?"
		&& getDialogAnswer() == "Playing video games"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n RYLOTH",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q14_NABOO"
	when Answer(
		d:dialog, d.getQuestion == "How do you spend your time together?"
		&& getDialogAnswer() == "Long talks"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n NABOO",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q14_MONCALA"
	when Answer(
		d:dialog, d.getQuestion == "How do you spend your time together?"
		&& getDialogAnswer() == "Eat sushi"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n MON CALA",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q12"
	when Answer(
		d:dialog, d.getQuestion == "Are you social?"
		&& getDialogAnswer() == "I prefer animals over people"
	)
	then
	Dialog tempDialog = new Dialog(
		"Choose an animal.",
		new String[] {"Squid","Bear"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q12_MONCALA"
	when Answer(
		d:dialog, d.getQuestion == "Choose an animal."
		&& getDialogAnswer() == "Squid"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n MON CALA",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q12_ENDOR"
	when Answer(
		d:dialog, d.getQuestion == "Choose an animal."
		&& getDialogAnswer() == "Bear"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n ENDOR",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q3_MONCALA"
	when Answer(
		d:dialog,d.getQuestion == "Sounds like you need to commune with nature." &&
		getDialogAnswer() == "OK but I'm not sleeping outside, rigth"
		)
	then
	Dialog td = new Dialog(
		"Your destination is:\n MON CALA",
		new String[] {"OK"}
	);
	String ta = window.askUser(td.getQuestion(),td.getAnswers());
	insert(new Answer(td,ta));
end

rule "Q3_ENDOR"
	when Answer(
		d:dialog,d.getQuestion == "Sounds like you need to commune with nature." &&
		getDialogAnswer() == "Yes"
		)
	then
	Dialog td = new Dialog(
		"Your destination is:\n ENDOR",
		new String[] {"OK"}
	);
	String ta = window.askUser(td.getQuestion(),td.getAnswers());
	insert(new Answer(td,ta));
end

rule "Q16"
	when Answer(
		d:dialog, d.getQuestion == "What line of work are you in?"
		&& getDialogAnswer() == "Business"
	)
	then
	Dialog tempDialog = new Dialog(
		"Who would you never do buisness with",
		new String[] {"Alderaan","A talking squid","Dugs or Toydarians"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q15"
	when Answer(
		d:dialog, d.getQuestion == "Who would you never do buisness with"
		&& getDialogAnswer() == "Alderaan"
	)
	then
	Dialog tempDialog = new Dialog(
		"Aw, too soon?",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q15_NABOO"
	when Answer(
		d:dialog, d.getQuestion =="Aw, too soon?"
		&& getDialogAnswer() == "OK"
	)
	then
	Dialog td = new Dialog(
		"Your destination is:\n NABOO",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(td.getQuestion(), td.getAnswers());
	insert(new Answer(td,userAnswer));
end

rule "Q15_MUSTAFAR"
	when Answer(
		d:dialog, d.getQuestion == "Who would you never do buisness with"
		&& getDialogAnswer() == "A talking squid"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n MUSTAFAR",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q15_CORUSCANT"
	when Answer(
		d:dialog, d.getQuestion == "Who would you never do buisness with"
		&& getDialogAnswer() == "Dugs or Toydarians"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n CORUSCANT",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q45"
	when Answer(
		d:dialog, d.getQuestion == "What line of work are you in?"
		&& getDialogAnswer() == "Retail"
	)
	then
	Dialog tempDialog = new Dialog(
		"Whats's the one thing you can't travel without?",
		new String[] {"A GoPro",
		"My brand-new hologram cell phone","My camera"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q45_MUSTAFAR"
	when Answer(
		d:dialog, d.getQuestion == "Whats's the one thing you can't travel without?"
		&& getDialogAnswer() == "A GoPro"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n MUSTAFAR",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q45_CORUSCANT"
	when Answer(
		d:dialog, d.getQuestion == "Whats's the one thing you can't travel without?"
		&& getDialogAnswer() == "My brand-new hologram cell phone"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n CORUSCANT",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q45_RYLOTH"
	when Answer(
		d:dialog, d.getQuestion == "Whats's the one thing you can't travel without?"
		&& getDialogAnswer() == "My camera"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n RYLOTH",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q43"
	when Answer(
		d:dialog, d.getQuestion == "What line of work are you in?"
		&& getDialogAnswer() == "Creative field"
	)
	then
	Dialog tempDialog = new Dialog(
		"What are you more inspired by?",
		new String[] {"Great artists before me", "Posters with eagles and inspirational quotes"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q42"
	when Answer(
		d:dialog, d.getQuestion == "What are you more inspired by?"
		&& getDialogAnswer() == "Posters with eagles and inspirational quotes"
	)
	then
	Dialog tempDialog = new Dialog(
		"Which motto do you live by?",
		new String[] {"There's always a bigger fish.", "Live long and prosper."}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q42_THIS"
	when Answer(
		d:dialog, d.getQuestion == "Which motto do you live by?"
		&& getDialogAnswer() == "Live long and prosper."
	)
	then
	Dialog tempDialog = new Dialog(
		"This is not the flowchart you're looking for",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q42_MONCALA"
	when Answer(
		d:dialog, d.getQuestion == "Which motto do you live by?"
		&& getDialogAnswer() == "There's always a bigger fish."
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n MON CALA",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q44"
	when Answer(
		d:dialog, d.getQuestion == "What are you more inspired by?"
		&& getDialogAnswer() == "Great artists before me"
	)
	then
	Dialog tempDialog = new Dialog(
		"Whose painting would you frame on your wall?",
		new String[] {"M.C.Escher", "Hokusai"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q44_RYKOTH"
	when Answer(
		d:dialog, d.getQuestion == "Whose painting would you frame on your wall?"
		&& getDialogAnswer() == "M.C.Escher"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n RYKOTH",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q44_MONCALA"
	when Answer(
		d:dialog, d.getQuestion == "Whose painting would you frame on your wall?"
		&& getDialogAnswer() == "Hokusai"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destination is:\n MON CALA",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end



rule "Q19"
	when Answer(
		d:dialog, d.getQuestion == "Mentally or physically?"
		&& getDialogAnswer() == "Mentally"
	)
	then
	Dialog tempDialog = new Dialog(
		"Beware. Anger, fear, aggression. The Dark Side are they.",
		new String[] {"I am the Dark Side.","Help me Obi-Wan Kenobi!"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q19_YOU"
	when Answer(
		d:dialog, d.getQuestion =="Beware. Anger, fear, aggression. The Dark Side are they."
		&& getDialogAnswer() == "I am the Dark Side."
	)
	then
	Dialog tempDialog = new Dialog(
		"You don't need a vacation. The Force will set you free.",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q20"
	when Answer(
		d:dialog, d.getQuestion == "Beware. Anger, fear, aggression. The Dark Side are they."
		&& getDialogAnswer() == "Help me Obi-Wan Kenobi!"
	)
	then
	Dialog tempDialog = new Dialog(
		"Clear your mind you must. How do you unwind?",
		new String[] {"Oil baths","Braid my hair","Listen to music","Sports"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q20_CORUSCANT"
	when Answer(
		d:dialog, d.getQuestion == "Clear your mind you must. How do you unwind?"
		&& getDialogAnswer() == "Oil baths"
	)
	then
		Dialog tempDialog = new Dialog(
		"Your destinations is:\nCoruscant",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q20_ENDOR"
	when Answer(
		d:dialog, d.getQuestion == "Clear your mind you must. How do you unwind?"
		&& getDialogAnswer() == "Braid my hair"
	)
	then
		Dialog tempDialog = new Dialog(
		"Your destinations is:\nEndor",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q21"
	when Answer(
		d:dialog, d.getQuestion == "Clear your mind you must. How do you unwind?"
		&& getDialogAnswer() == "Listen to music"
	)
	then
		Dialog tempDialog = new Dialog(
		"What type?",
		new String[] {"Instrumental","Rock","Pop"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q22"
	when Answer(
		d:dialog, d.getQuestion == "What type?"
		&& getDialogAnswer() == "Instrumental"
	)
	then
		Dialog tempDialog = new Dialog(
		"Jhon Williams or Danny Elfman?",
		new String[] {"Jhon Williams","Danny Elfman"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q22_ENDOR"
	when Answer(
		d:dialog, d.getQuestion == "Jhon Williams or Danny Elfman?"
		&& getDialogAnswer() == "Jhon Williams"
	)
	then
		Dialog tempDialog = new Dialog(
		"Your destinations is:\nEndor",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q22_CORUSCANT"
	when Answer(
		d:dialog, d.getQuestion == "Jhon Williams or Danny Elfman?"
		&& getDialogAnswer() == "Danny Elfman"
	)
	then
		Dialog tempDialog = new Dialog(
		"Your destinations is:\nCoruscant",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q21_MALASTARE"
	when Answer(
		d:dialog, d.getQuestion == "What type?"
		&& getDialogAnswer() == "Rock"
	)
	then
		Dialog tempDialog = new Dialog(
		"Your destinations is:\nMalastare",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q21_CORUSCANT"
	when Answer(
		d:dialog, d.getQuestion == "What type?"
		&& getDialogAnswer() == "Pop"
	)
	then
		Dialog tempDialog = new Dialog(
		"Your destinations is:\nCoruscant",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q24"
	when Answer(
		d:dialog, d.getQuestion == "Clear your mind you must. How do you unwind?"
		&& getDialogAnswer() == "Sports"
	)
	then
	Dialog tempDialog = new Dialog(
		"Do you play or watch?",
		new String[] {"Play","Watch"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q24_JAKKU"
	when Answer(
		d:dialog, d.getQuestion == "Do you play or watch?"
		&& getDialogAnswer() == "Watch"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nJakku",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q29"
	when Answer(
		d:dialog, d.getQuestion == "Do you play or watch?"
		&& getDialogAnswer() == "Play"
	)
	then
	Dialog tempDialog = new Dialog(
		"Podracers or lavaracers?",
		new String[] {"Podracers","Lavaracers"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q29_MALASTARE"
	when Answer(
		d:dialog, d.getQuestion == "Podracers or lavaracers?"
		&& getDialogAnswer() == "Podracers"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nMalastare",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q29_MUSTAFAR"
	when Answer(
		d:dialog, d.getQuestion == "Podracers or lavaracers?"
		&& getDialogAnswer() == "Lavaracers"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nMustafar",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end
rule "Q27"
	when Answer(
		d:dialog, d.getQuestion == "Mentally or physically?"
		&& getDialogAnswer() == "Physically"
	)
	then
	Dialog tempDialog = new Dialog(
		"Do you have a death wish?",
		new String[] {"Yes","No"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q26"
	when Answer(
		d:dialog, d.getQuestion == "Do you have a death wish?"
		&& getDialogAnswer() == "No"
	)
	then
	Dialog tempDialog = new Dialog(
		"Do you drink?",
		new String[] {"Yes","Does blue milk count?"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q26_NABOO"
	when Answer(
		d:dialog, d.getQuestion == "Do you drink?"
		&& getDialogAnswer() == "Does blue milk count?"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nNaboo",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q18"
	when Answer(
		d:dialog, d.getQuestion == "Do you drink?"
		&& getDialogAnswer() == "Yes"
	)
	then
	Dialog tempDialog = new Dialog(
		"At clubs or bars?",
		new String[] {"Clubs","Bars"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q18_CORUSCANT"
	when Answer(
		d:dialog, d.getQuestion == "At clubs or bars?"
		&& getDialogAnswer() == "Clubs"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nCoruscant",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q17"
	when Answer(
		d:dialog, d.getQuestion == "At clubs or bars?"
		&& getDialogAnswer() == "Bars"
	)
	then
	Dialog tempDialog = new Dialog(
		"What are you ordering?",
		new String[] {"Mai Tai","An okay scotch","Fireball shots","Knockback rum"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q17_ENDOR"
	when Answer(
		d:dialog, d.getQuestion == "What are you ordering?"
		&& getDialogAnswer() == "An okay scotch"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nEndor",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q17_MONCALA"
	when Answer(
		d:dialog, d.getQuestion == "What are you ordering?"
		&& getDialogAnswer() == "Mai Tai"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nMon Cala",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q17_MUSTAFAR"
	when Answer(
		d:dialog, d.getQuestion == "What are you ordering?"
		&& getDialogAnswer() == "Fireball shots"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nMustafar",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q17_JAKKU"
	when Answer(
		d:dialog, d.getQuestion == "What are you ordering?"
		&& getDialogAnswer() == "Knockback rum"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nJakku",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q28"
	when Answer(
		d:dialog, d.getQuestion == "Do you have a death wish?"
		&& getDialogAnswer() == "Yes"
	)
	then
	Dialog tempDialog = new Dialog(
		"How do you want to die?",
		new String[] {"In a knife fight","In a fiery explosion"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q28_MALASTARE"
	when Answer(
		d:dialog, d.getQuestion == "How do you want to die?"
		&& getDialogAnswer() == "In a knife fight"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nMalastare",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q28_MUSTAFAR"
	when Answer(
		d:dialog, d.getQuestion == "How do you want to die?"
		&& getDialogAnswer() == "In a fiery explosion"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nMustafar",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q33"
	when Answer(
		d:dialog, d.getQuestion == "Search your feelings. Why are you traveling"
		&& getDialogAnswer() == "I just want to teleport off this rock"
	)
	then
	Dialog tempDialog = new Dialog(
		"What's your midi-chlorian count?",
		new String[] {"DGAF! No mystical energy field controls my destiny","Off the charts"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q30"
	when Answer(
		d:dialog, d.getQuestion == "What's your midi-chlorian count?"
		&& getDialogAnswer() == "DGAF! No mystical energy field controls my destiny"
	)
	then
	Dialog tempDialog = new Dialog(
		"What controls your destiny?",
		new String[] {"Adrenaline","Money","Love"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q31"
	when Answer(
		d:dialog, d.getQuestion == "What controls your destiny?"
		&& getDialogAnswer() == "Money"
	)
	then
	Dialog tempDialog = new Dialog(
		"If money is what you love, then that's what you'll receive.\nAre you the gambling type?",
		new String[] {"Yes, never tell me the odds","No"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q25"
	when Answer(
		d:dialog, d.getQuestion == "If money is what you love, then that's what you'll receive.\nAre you the gambling type?"
		&& getDialogAnswer() == "No"
	)
	then
	Dialog tempDialog = new Dialog(
		"Are you holding?",
		new String[] {"Who's asking?","No"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q30_5"
	when Answer(
		d:dialog, d.getQuestion == "What controls your destiny?"
		&& getDialogAnswer() == "Adrenaline"
	)
	then
	Dialog tempDialog = new Dialog(
		"Do you have a death wish?",
		new String[] {"Yes","No"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q31_5"
	when Answer(
		d:dialog, d.getQuestion == "If money is what you love, then that's what you'll receive.\nAre you the gambling type?"
		&& getDialogAnswer() == "Yes, never tell me the odds"
	)
	then
	Dialog tempDialog = new Dialog(
		"Podracers or lavaracers?",
		new String[] {"Podracers","Lavaracers"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q25_5"
	when Answer(
		d:dialog, d.getQuestion == "Are you holding?"
		&& getDialogAnswer() == "No"
	)
	then
	Dialog tempDialog = new Dialog(
		"Do you drink?",
		new String[] {"Yes","Does blue milk count?"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q23"
	when Answer(
		d:dialog, d.getQuestion == "Are you holding?"
		&& getDialogAnswer() == "Who's asking?"
	)
	then
	Dialog tempDialog = new Dialog(
		"You may want to rethinkyour life choices",
		new String[] {"Help me Obi-Wan Kenobi!","Your jedi mind tricks don't work on me"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q23_MALASTARE"
	when Answer(
		d:dialog, d.getQuestion == "You may want to rethinkyour life choices"
		&& getDialogAnswer() == "Your jedi mind tricks don't work on me"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nMalastare",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q32"
	when Answer(
		d:dialog, d.getQuestion == "What controls your destiny?"
		&& getDialogAnswer() == "Love"
	)
	then
	Dialog tempDialog = new Dialog(
		"Are you in a serious relationship?",
		new String[] {"No, she died giving birth to twins","Yes","I don't know... You think a princess and a guy like me..."}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q32_MALASTARE"
	when Answer(
		d:dialog, d.getQuestion == "Are you in a serious relationship?"
		&& getDialogAnswer() == "No, she died giving birth to twins"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nMalastare",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q34"
	when Answer(
		d:dialog, d.getQuestion == "Are you in a serious relationship?"
		&& getDialogAnswer() == "Yes"
	)
	then
	Dialog tempDialog = new Dialog(
		"The love of your life has been taken prisoner. Do you risk your life to save theirs?",
		new String[] {"No, better them than me","I'm already holding my thermal detonator"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q20_5"
	when Answer(
		d:dialog, d.getQuestion == "You may want to rethinkyour life choices"
		&& getDialogAnswer() == "Help me Obi-Wan Kenobi!"
	)
	then
	Dialog tempDialog = new Dialog(
		"Clear your mind you must. How do you unwind?",
		new String[] {"Oil baths","Braid my hair","Listen to music","Sports"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q34_ENDOR"
	when Answer(
		d:dialog, d.getQuestion == "The love of your life has been taken prisoner. Do you risk your life to save theirs?"
		&& getDialogAnswer() == "No, better them than me"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nEndor",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q35"
	when Answer(
		d:dialog, d.getQuestion == "The love of your life has been taken prisoner. Do you risk your life to save theirs?"
		&& getDialogAnswer() == "I'm already holding my thermal detonator"
	)
	then
	Dialog tempDialog = new Dialog(
		"Sounds like you're up for an adventure",
		new String[] {"Yes","Those days are long behind us"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q35_RYLOTH"
	when Answer(
		d:dialog, d.getQuestion == "Sounds like you're up for an adventure"
		&& getDialogAnswer() == "Yes"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nRyloth",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q35_NABOO"
	when Answer(
		d:dialog, d.getQuestion == "Sounds like you're up for an adventure"
		&& getDialogAnswer() == "Those days are long behind us"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nNaboo",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q36"
	when Answer(
		d:dialog, d.getQuestion == "Are you in a serious relationship?"
		&& getDialogAnswer() == "I don't know... You think a princess and a guy like me..."
	)
	then
	Dialog tempDialog = new Dialog(
		"Would you kiss your sibling to make them jealous?",
		new String[] {"Yes","No"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q37"
	when Answer(
		d:dialog, d.getQuestion == "Would you kiss your sibling to make them jealous?"
		&& getDialogAnswer() == "Yes"
	)
	then
	Dialog tempDialog = new Dialog(
		"You're gonna regret that",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q37_RYLOTH"
	when Answer(
		d:dialog, d.getQuestion == "You're gonna regret that"
		&& getDialogAnswer() == "OK"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nRyloth",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q36_NABOO"
	when Answer(
		d:dialog, d.getQuestion == "Would you kiss your sibling to make them jealous?"
		&& getDialogAnswer() == "No"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nNaboo",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q38"
	when Answer(
		d:dialog, d.getQuestion == "What's your midi-chlorian count?"
		&& getDialogAnswer() == "Off the charts"
	)
	then
	Dialog tempDialog = new Dialog(
		"Great kid, don't get cocky.\nAre you searching for something or hiding from something?",
		new String[] {"Hiding","Searching"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q41"
	when Answer(
		d:dialog, d.getQuestion == "Great kid, don't get cocky.\nAre you searching for something or hiding from something?"
		&& getDialogAnswer() == "Searching"
	)
	then
	Dialog tempDialog = new Dialog(
		"Searching or scavenging?",
		new String[] {"Scavenging","Searching"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q41_JAKKU"
	when Answer(
		d:dialog, d.getQuestion == "Searching or scavenging?"
		&& getDialogAnswer() == "Scavenging"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nJakku",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q41_ILUM"
	when Answer(
		d:dialog, d.getQuestion == "Searching or scavenging?"
		&& getDialogAnswer() == "Searching"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nIlum",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q39"
	when Answer(
		d:dialog, d.getQuestion == "Great kid, don't get cocky.\nAre you searching for something or hiding from something?"
		&& getDialogAnswer() == "Hiding"
	)
	then
	Dialog tempDialog = new Dialog(
		"From what?",
		new String[] {"Don't worry about it","A slimy piece of worm-ridden filth"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q39_JAKKU"
	when Answer(
		d:dialog, d.getQuestion == "From what?"
		&& getDialogAnswer() == "Don't worry about it"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nJakku",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q40"
	when Answer(
		d:dialog, d.getQuestion == "From what?"
		&& getDialogAnswer() == "A slimy piece of worm-ridden filth"
	)
	then
	Dialog tempDialog = new Dialog(
		"Lightspeed!",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end

rule "Q40_ENDOR"
	when Answer(
		d:dialog, d.getQuestion == "Lightspeed!"
		&& getDialogAnswer() == "OK"
	)
	then
	Dialog tempDialog = new Dialog(
		"Your destinations is:\nEndor",
		new String[] {"OK"}
	);
	String userAnswer = window.askUser(tempDialog.getQuestion(), tempDialog.getAnswers());
	insert(new Answer(tempDialog,userAnswer));
end





