package com.sample
 
import com.sample.Window;

global Window window;

declare Dialog
	question: String
	answers: String[]
end

declare Answer
	dialog: Dialog
	dialogAnswer: String
end

rule "Init"
	when
	then
		insert(
		new Dialog(
		"Search your feelings. Why are you traveling",
		new String[] {		"Vacation? Now that's a word I haven't heard in a long, long time.",
		"I just want to teleport off this rock"}
		));
		window = new Window();
		insert(window);
end

rule "D"
	when a: Dialog()
	then 
		String odp = window.askUser(a.getQuestion(),a.getAnswers());
		Answer ans = new Answer(a, odp);
		insert(ans);
end

rule "Q2"
	when Answer(
		d: dialog, 
		d.getQuestion() == "Search your feelings. Why are you traveling"
		&& getDialogAnswer() == "Vacation? Now that's a word I haven't heard in a long, long time.")
	then
	Dialog td = new Dialog(
		"What could you use a break from?",
		new String[] {"The same faces at the cantina","The city","Work"});
	String ta = window.askUser(td.getQuestion(),td.getAnswers());
	insert(new Answer (td,ta));
end

rule "Q5"
	when Answer(
		d: dialog, d.getQuestion == "What could you use a break from?" 
		&& getDialogAnswer() == "The same faces at the cantina"
		)
	then 
	Dialog td = new Dialog(
		"Are you self-destructive?",
		 new String[]{"No","Yes"}
		 );
	String ta = window.askUser(td.getQuestion(),td.getAnswers());
	insert(new Answer( td,ta));
end

rule "Q3"
	when Answer(
		d:dialog,d.getQuestion == "What could you use a break from?" &&
		getDialogAnswer() == "The city"
		)
	then
	Dialog td = new Dialog(
		"Sounds like you need to commune with nature.",
		new String[] {"OK but I'm not sleeping outside, rigth","Yes"}
		);
	String ta = window.askUser(td.getQuestion(),td.getAnswers());
	insert(new Answer(td,ta));
end